const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../js/app.status-source.js'),'utf8');
const html=fs.readFileSync(path.join(__dirname,'../login.html'),'utf8');
const storage=()=>{const values=new Map();return{getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,String(value)),removeItem:key=>values.delete(key),clear:()=>values.clear()};};
function harness(){const c={localStorage:storage(),sessionStorage:storage(),Date,JSON,Number,ADMIN_SESSION_TTL:30*86400000,REP_SESSION_KEY:'dad_rep_session_v1',ADMIN_SESSION_KEY:'dad_admin_session_v2',LEGACY_ADMIN_KEYS:[],currentRepId:null,currentRepName:null,btoa:()=> 'fixture-token',encodeURIComponent};vm.createContext(c);vm.runInContext(source.slice(source.indexOf('function saveAdminSession('),source.indexOf('function getCurrentFilteredAllOrders('))+source.slice(source.indexOf('function getRememberedRepSession('),source.indexOf('\nconst repSelect =')),c);return c;}
test('remembered representative session survives a new browser session; logout clears it',()=>{const c=harness();c.saveRepSession('rep1','Representative',true);c.sessionStorage.clear();assert.equal(c.loadRepSession(),true);assert.equal(c.currentRepId,'rep1');c.clearRepSession();assert.equal(c.loadRepSession(),false);assert.equal(c.localStorage.getItem(c.REP_SESSION_KEY),null);});
test('unchecking remember removes an older persistent session',()=>{const c=harness();c.saveRepSession('rep1','Representative',true);c.saveRepSession('rep1','Representative',false);c.sessionStorage.clear();assert.equal(c.loadRepSession(),false);});
test('expired, malformed and future representative sessions do not restore',()=>{for(const raw of ['bad',JSON.stringify({repId:'rep1',repName:'Rep',remember:true,savedAt:Date.now()-31*86400000}),JSON.stringify({repId:'rep1',repName:'Rep',remember:true,savedAt:Date.now()+86400000})]){const c=harness();c.localStorage.setItem(c.REP_SESSION_KEY,raw);assert.equal(c.loadRepSession(),false);assert.equal(c.localStorage.getItem(c.REP_SESSION_KEY),null);}});
for(const role of ['manager','reports'])test(`${role}: remember uses persistent storage; unchecked uses tab storage`,()=>{const c=harness();c.saveAdminSession('Account',role,true);c.sessionStorage.clear();assert.equal(c.getAdminSession().type,role);c.saveAdminSession('Account',role,false);assert.equal(c.localStorage.getItem(c.ADMIN_SESSION_KEY),null);c.sessionStorage.clear();assert.equal(c.getAdminSession(),null);});
function redirectHarness(local,session,search=''){let destination='';const c={localStorage:local,sessionStorage:session,URLSearchParams,Date,Number,document:{title:'Login'},window:{location:{search,pathname:'/login.html',replace:url=>{destination=url;}},history:{replaceState(){}}}};vm.createContext(c);vm.runInContext(html.match(/<script>\s*([\s\S]*?)<\/script>/)[1],c);return destination;}
test('login restores remembered representative, supervisor and manager destinations',()=>{let c=harness();c.saveRepSession('rep1','Rep',true);c.sessionStorage.clear();assert.equal(redirectHarness(c.localStorage,c.sessionStorage),'order.html');for(const [type,dest]of[['manager','supervisor.html'],['reports','reports.html']]){c=harness();c.saveAdminSession('Account',type,true);assert.equal(redirectHarness(c.localStorage,c.sessionStorage),dest);}});
test('expired admin session does not create a login redirect loop',()=>{const c=harness();c.localStorage.setItem(c.ADMIN_SESSION_KEY,JSON.stringify({name:'Account',type:'manager',token:'fixture',remember:true,savedAt:Date.now()-31*86400000}));assert.equal(redirectHarness(c.localStorage,c.sessionStorage),'');});
test('both forms use native submit buttons and submit handlers',()=>{for(const [form,button,fn]of[['repLoginForm','startOrderBtn','submitRepresentativeLogin'],['adminLoginForm','confirmAdminLoginBtn','submitAdminLogin']]){assert.match(html,new RegExp(`id="${button}" type="submit"`));let bound;const context={getEl:id=>id===form?{addEventListener:(event,handler)=>{assert.equal(event,'submit');bound=handler;}}:null,[fn]:()=>{},startOrderBtn:{},confirmAdminLoginBtn:{}};vm.createContext(context);const start=source.indexOf(form==='repLoginForm'?'const representativeLoginForm =':'const administratorLoginForm =');const end=source.indexOf(form==='repLoginForm'?'\n\nif (submitOrderBtn)':"\ngetEl('selectAllAllOrders')",start);vm.runInContext(source.slice(start,end),context);assert.equal(bound,context[fn]);}});
test('successful role changes clear the conflicting previous login session',async()=>{const c=harness();c.saveRepSession('old-rep','Old Rep',true);const controls={adminPasswordInput:{value:'fixture-password'},rememberAdmin:{checked:true}};Object.assign(c,{getEl:id=>controls[id],selectedAdminType:'manager',selectedAdminName:'Supervisor',location:{search:''},window:{location:{}},showToast(){},URLSearchParams,btoa:()=> 'MjAyNjA0'});vm.runInContext(source.slice(source.indexOf('function submitAdminLogin('),source.indexOf('const administratorLoginForm =')),c);c.submitAdminLogin({preventDefault(){}});assert.equal(c.localStorage.getItem(c.REP_SESSION_KEY),null);assert.equal(c.sessionStorage.getItem('repId'),null);assert.equal(c.getAdminSession().name,'Supervisor');});
