import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const values = new Map(), timers = [];
const storage = { get length(){return values.size;}, key:i=>[...values.keys()][i], getItem:key=>values.get(key)||null, setItem:(key,value)=>values.set(key,value), removeItem:key=>values.delete(key) };
const env = { location:{href:`https://baselghanem.github.io/OrderingSystem/Returns/reports.html`}, document:{title:`تجريبي`,addEventListener(){}}, localStorage:storage, setTimeout:fn=>{timers.push(fn);return timers.length;}, addEventListener(){} };
const module = new vm.SourceTextModule(fs.readFileSync(new URL('../js/read-meter-core.js',import.meta.url),'utf8'), { context:vm.createContext({URL,Date,Math,Error,Promise,Proxy,Reflect,structuredClone,setTimeout,globalThis:{}}) });
await module.link(()=>{});await module.evaluate();const meter=module.namespace.makeMeter(env);
const querySnapshot=(size,fromCache=false,changes=[])=>({size,metadata:{fromCache,hasPendingWrites:false},docChanges:()=>changes});
const snapshot=querySnapshot(1325);const reference={path:`pharmacies/private-code`};
assert.equal(await meter.wrapRead(async()=>snapshot,`getDocs`)(reference),snapshot);
await meter.wrapRead(async()=>querySnapshot(100,true),`getDocs`)(reference);
await meter.wrapRead(async()=>querySnapshot(0),`getDocs`)(reference);
const failure=Object.assign(Error(`secret error text`),{code:`resource-exhausted`});
await assert.rejects(meter.wrapRead(async()=>{throw failure;},`getDocs`)(reference),error=>error===failure);
let handler,unsubscribed=0;let received=[];
const listen=meter.wrapListen((target,...args)=>{handler=typeof args[0]===`function`?{next:args[0],error:args[1]}:args[0];return ()=>unsubscribed++;});
const unsub=listen(reference,snap=>received.push(snap));
handler.next(querySnapshot(4,true));handler.next(querySnapshot(4,false));handler.next(querySnapshot(4,false,[{type:`modified`},{type:`removed`}]));
assert.equal(received.length,3);unsub();assert.equal(unsubscribed,1);
let observerThis;const observer={next(){observerThis=this;},error(error){assert.equal(error,failure);}};
listen(reference,observer);handler.next(querySnapshot(2));assert.equal(observerThis,observer);handler.error(failure);
let rawSet=0,txCalls=0;const transaction=meter.wrapTransaction(async(_,action)=>{txCalls++;const tx={get:async()=>({exists:()=>true,metadata:{fromCache:false}}),set(){rawSet++;return this;}};return action(tx);});
assert.equal(await transaction({},async tx=>{await tx.get(reference);tx.set(reference,{});return `saved`;}),`saved`);assert.equal(rawSet,1);assert.equal(txCalls,1);
meter.flush();const report=meter.report();assert.equal(report.page,`Returns/reports.html`);
const rows=Object.values(report.rows),sum=f=>rows.reduce((n,r)=>n+r[f],0);
assert.equal(sum(`serverDocs`),1333);assert.equal(sum(`cacheDocs`),104);assert.equal(sum(`emptyResults`),1);assert.equal(sum(`errors`),2);assert.equal(sum(`active`),0);
assert.ok(!JSON.stringify(report).includes(`private-code`));assert.ok(!JSON.stringify(report).includes(`secret error text`));assert.equal(values.size,1);
const blockedEnv={...env,localStorage:{get length(){throw Error(`denied`);},setItem(){throw Error(`denied`);}}};
const blocked=module.namespace.makeMeter(blockedEnv);assert.equal(await blocked.wrapRead(async()=>snapshot,`getDocs`)(reference),snapshot);blocked.flush();
console.log(`Read diagnostics tests passed: unchanged snapshots, cache separation, incremental changes, observer binding, errors, unsubscribe, transaction behavior, privacy and blocked local storage.`);
